name: CI

on:
  push:
    branches:
    - master
    - release
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Lint and build
      run: |
        npm run lint
        npm run build
